### ISSUE TITLE
[Quilt 1.20.1] Incompatibility with Visual Workbench mod

### ISSUE THREAD

**Issue by CarlMichaelFabe** [sleepingdragoninn/inventory-tabs#20]
This is the mod in question: https://modrinth.com/mod/visual-workbench

When the crafting table is empty, changing tabs to it works normally. 

But when you put an item inside the workbench, it bugs out. With the item inside the workbench, switching to another tab and switching back to the workbench gets the tabs stuck and you can't click on any tabs anymore.

https://github.com/sisby-folk/inventory-tabs/assets/116660522/293d8761-4b24-4f75-9e7e-412fde90fe0e

**Comment by sleepingdragoninn** [comment]
Visual workbench registers a block entity for crafting benches, meaning they're no longer unique per type - so swap the provider should be changed to `inventory_tabs:block_simple`.

The proper issue is here in inventory-tabs (yarn):

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/b3b3228c-9cd2-400c-bc82-884d1a50c222)

and here in visualworkbench (moj):

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/a1766ed3-4a46-46cb-bb01-94f68e36194b)

by the time `updateSlotStacks` is called (after the constructor), the revision of the screen is already `10`, instead of `1`, because each individual slot has been set in a way that increments the revision, instead of all slots being set at once.

This is resolvable on visual workbench's side so feel free to alert them there (they just need to not end up at rev 10 - which I think they might like to do, as it matches vanilla containers), but we should be able to implement a workaround on our side as well by checking if the screen is freshly constructed.

**Comment by sleepingdragoninn** [comment]
workaround implemented in 1.1.3:


https://github.com/sisby-folk/inventory-tabs/assets/55819817/30d774e2-9069-4ef8-aaa5-1e3a70e4d11e

**Comment by CarlMichaelFabe** [comment]
Thank you for the fix!
