### ISSUE TITLE
Tabs Are Misaligned With Small Ships Mod

### ISSUE THREAD

**Issue by 24-7-testing** [sleepingdragoninn/inventory-tabs#33]
Reference Issue #32 for most of the initial details. After the fix was applied, I checked to see if it worked. The game no longer crashes, but the tabs do not appear in the correct location. See pic attached.
![Tabs Misaligned](https://github.com/sisby-folk/inventory-tabs/assets/50222101/4853081d-796f-4040-b229-090234c6f546)

**Comment by sleepingdragoninn** [comment]
This is back on Small Ships end now - they need to set their screen `y` to reflect the larger inventory panel instead of their small side panel (they can use their own custom field for that) - this is what inventory tabs uses to find the top left and width of the panel.

Here's the snippet:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/1ab4b914-8fc8-4bea-854e-1b76e2e6523e)

**Comment by 24-7-testing** [comment]
Good to know! I'll go file a report with them then. Thanks for the info!

**Comment by sleepingdragoninn** [comment]
I'll note though, it seems like this screen doesn't properly support inventory tabs because of the aforementioned overriding of `init()` - you can tell because the "ship" tab icon isn't lit up indicating it's the current screen, and because of the previous crash issue.

For this, you can simply disable the screen in the inventory tabs config - feel free to read the [part of the readme](https://github.com/sisby-folk/inventory-tabs?#modpack-configuration) covering this.
