### ISSUE TITLE
Tech Reborn machines can't be opened

### ISSUE THREAD

**Issue by TeslaP09** [sleepingdragoninn/inventory-tabs#39]
When running Inventory Tabs together with Tech Reborn, none of Reborn's interfaces can be opened. Right clicking on a machine doesn't do anything, except inducing a small blur when an inventory blur mod is installed, indicating that the inventory is trying to be opened, but the action gets cancelled immediately. I discovered the issue in my modpack, but the issue persists when isolating the two mods. The log says that the 'handlerId' is null, so maybe this is an issue with Tech Reborn, however turning off default support of every screen in the inventory tabs config or trying to enter the screens manually and disabling them doesn't do anything either, whereas it does work for other mods.
[latest.log](https://github.com/sisby-folk/inventory-tabs/files/14702160/latest.log)

Inventory Tabs 1.1.8
Minecraft 1.20.1
Fabric Loader 0.15.6 (also tested on .7)
Fabric API 0.92.0

**Comment by sleepingdragoninn** [comment]
This is definitely related - in order to check if a screen should show tabs or not, it checks its screen handler ID. From what you've described, tech reborn is opening screens that don't have screen handler IDs, which is usually only true of the creative screen and the inventory screen.

Definitely solvable on their end by adding IDs, but we should revise our code so it doesn't hang when loading screens without IDs.
